name: mlcourse
channels:
  - pytorch
  - nvidia
  - conda-forge
  - fastai
  - mhoelzl
  - defaults
dependencies:
  - python[version='>=3.9']
  # Delete the following two lines on a Mac
  - cuda
  - cudnn
  - autopep8
  - black
  - charset-normalizer
  - cookiecutter
  - datasets
  - fastapi
  - graphviz
  - ipykernel
  - kaggle
  # Remove this if it causes problems!
  - fastai
  - ftfy
  - mypy
  - jinja2
  - jupyter
  - jupytext
  - matplotlib
  - nbex
  - numba
  - numpy
  - pandas
  - papermill
  - pip
  - pyarrow
  - pydot
  - pytest
  - pytest-cov
  - python-build
  - pytorch
  - rise
  - scikit-learn
  - scipy
  - seaborn
  - skorch
  - spacy[version='>=3']
  - statsmodels
  - streamlit
  - torchtext
  - torchvision
  - transformers
  - typer
  - pip:
    - pytorch_model_summary
